version: '2.1'
services:
  examples-api:
    build: .
    image: dafrodriguezro/2b_api_gateway
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      AUTHENTICATION_URL: '192.168.99.101'
      AUTHENTICATION_PORT: '4000'
      AUTHENTICATION_ENTRY: 'authenticaion/'
      EXAMPLES_URL: '35.196.170.89'
      EXAMPLES_PORT: '4001'
      EXAMPLES_ENTRY: 'examples/'
      UNITS_ENTRY: 'units/'
      TODAYSLESSON_URL: '192.168.99.101'
      TODAYSLESSON_PORT: '4002'
      TODAYSLESSON_ENTRY: 'todayslesson/'
      MAILER_URL: '192.168.99.101'
      MAILER_PORT: '4003'
      MAILER_ENTRY: 'mailes/'
      CHAT_URL: '192.168.99.101'
      CHAT_PORT: '4004'
      CHAT_ENTRY: 'chat/'
      EXERCISES_URL: '192.168.99.101'
      EXERCISES_PORT: '4040'
      EXERCISES_ENTRY: 'exercises/'
    ports:
      - '5000:5000'
