version: '2'
services:
  api-gateway:
    image: dafrodriguezro/2b_api
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      AUTHENTICATION_PORT: '4000'
      AUTHENTICATION_ENTRY: 'user_token/'
      EXAMPLES_PORT: '4001'
      EXAMPLES_ENTRY: 'examples/'
      UNITS_ENTRY: 'units/'
      TODAYSLESSON_PORT: '4002'
      TODAYSLESSON_ENTRY: 'todayslessons'
      MAILER_PORT: '4003'
      MAILER_ENTRY: 'messages/'
      CHAT_PORT: '4004'
      CHAT_ENTRY: 'chat/'
      AWARDS_PORT: '4005'
      AWARDS_ENTRY: 'awards/'
      EXERCISES_PORT: '4040'
      EXERCISES_ENTRY: 'exercises/'
    ports:
      - '5000:5000'
